change the name of model types#7
AKitavtsev/server-post pull request #9
Opened 2021-10-05 19:21 UTC by AKitavtsev

2021-10-05 19:22 UTC, AKitavtsev commented
Попробовал объяснить, что для чего. Ну, не знаю, как получилось

2021-10-06 04:16 UTC, kelizarov requested changes

2021-10-06 04:16 UTC, kelizarov commented on src/Models/Author.hs
> +data ForCreateAuthor =
Возможно `Raw*модель*` будет уместнее тут, типа имеется ввиду что мы тут храним сырые данные, которые нам пришли из вне и мы хотим их использовать для создания моделей в БД.

2021-10-06 11:14 UTC, olegromashin commented on src/Models/Draft.hs
> +  , ForShowDraf(..)
*Draft

2021-10-06 16:09 UTC, AKitavtsev commented on src/Models/Draft.hs
> +  , ForShowDraf(..)
Raw, так Raw, Draft, так Draft.
Спасибо, исполнил

2021-10-07 12:03 UTC, merged